# Generated by Django 4.0.3 on 2022-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('numero_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('importe_factura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
