# Generated by Django 4.0.3 on 2022-04-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDeServicios',
            fields=[
                ('numero_comprobante', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_pagado', models.FloatField()),
                ('check_pago', models.BooleanField()),
            ],
        ),
    ]
