# Generated by Django 4.0.3 on 2022-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('numero_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('importe_factura', models.FloatField()),
                ('vencimiento_factura', models.DateField()),
            ],
        ),
    ]
